{"uuid": "102df9df-94f3-482e-ab30-316689480265", "children": ["14f8a640-854d-43f4-93be-725dbfe2416f"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"D:\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Projects\\Ktp\\tests\\conftest.py\", line 17, in browser\n    driver = webdriver.chrome(options=chrome_options)\n"}, "start": 1594901203082, "stop": 1594901203082}], "start": 1594901203081, "stop": 1594901203099}