{"uuid": "3d3dd009-b369-45be-988b-5c0f750ee2c4", "children": ["59e15864-99cc-4aca-8259-148952222a82", "e3e7189a-5217-4a71-b299-d86a6d467c6c", "8d5fdf80-0f21-437a-af6d-65b2086f7be9", "d65cfec6-2bb3-46a6-87ae-1655f930f79e"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"D:\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Projects\\Ktp\\tests\\conftest.py\", line 17, in browser\n    driver = webdriver.chrome(options=chrome_options)\n"}, "start": 1594901202947, "stop": 1594901202947}], "start": 1594901202947, "stop": 1594901203028}