{"uuid": "8627d8e2-8116-4e50-bd2e-cbbdeed66238", "children": ["3959c013-2748-469a-a247-562f6d7ec7ee"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"D:\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Projects\\Ktp\\tests\\conftest.py\", line 17, in browser\n    driver = webdriver.chrome(options=chrome_options)\n"}, "start": 1594901203111, "stop": 1594901203111}], "start": 1594901203111, "stop": 1594901203127}