{"uuid": "9f868f6f-ecc8-45c8-889b-2109e5479cd1", "children": ["73637a92-25f5-448e-88fd-2ff5072ac4e3"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"D:\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Projects\\Ktp\\tests\\conftest.py\", line 17, in browser\n    driver = webdriver.chrome(executable_path=r\"C:\\Users\\Administrator\\AppData\\Local\\Google\\Chrome\\Application\\chromedriver.exe\", options=chrome_options)\n"}, "start": 1594900804570, "stop": 1594900804570}], "start": 1594900804570, "stop": 1594900804586}