{"uuid": "20471481-348d-409e-8592-207276db8315", "children": ["046bc958-6a93-4b9d-acd5-fc1f5fdba927"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"D:\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Projects\\Ktp\\tests\\conftest.py\", line 17, in browser\n    driver = webdriver.chrome(executable_path=r\"C:\\Users\\Administrator\\AppData\\Local\\Google\\Chrome\\Application\\chromedriver.exe\", options=chrome_options)\n"}, "start": 1594900804526, "stop": 1594900804526}], "start": 1594900804526, "stop": 1594900804542}